apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "brigade-vsts-gateway.name" . }}
  labels:
    app: {{ template "brigade-vsts-gateway.name" . }}
    chart: {{ template "brigade-vsts-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "brigade-vsts-gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "brigade-vsts-gateway.name" . }}
        release: {{ .Release.Name }}
        role: gateway
    spec:
      serviceAccountName: {{ template "brigade-vsts-gateway.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/usr/bin/gateway"]
          args: ["--namespace", {{.Values.namespace | quote}}]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
