replicaCount: 1
namespace: default

rbac:
  enabled: true

image:
  repository: radumatei/brigade-vsts-gateway
  tag: edge
  pullPolicy: Always

service:
  type: LoadBalancer
  internalPort: 8080
  externalPort: 80


# for Azure vsts you must have TLS ingress
# more information here - https://docs.microsoft.com/en-us/azure/event-grid/security-authentication
ingress:
  enabled: false
# by default, this chart uses TLS the annotations for kube-lego and nginx-ingress
# if you have a different ingress controller, make sure to change them in ingress.yaml

  # annotations:
  #   kubernetes.io/tls-acme: "true"
  #   kubernetes.io/ingress.class: "nginx"
  host: <your-HTTPS-endpoint>
